const SUPABASE_URL='https://vqxjedlvphxgndhfugqm.supabase.co';
const SUPABASE_KEY='sb_publishable_q3iDOodA4cXBa4MJLTsOIA_pb2l5Hz0';
const PRODUCTION_URL='https://alexthezero.github.io/member-portal/';
const AVATAR_BUCKET='avatars';
const FAMILY_CODE='CAMPFIRE-2026';
const supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);
const authView=$('auth-view'),dashboardView=$('dashboard-view'),messageBox=$('message'),dashboardMessage=$('dashboard-message');
let currentUser=null,currentMembership=null,resolvedAvatarUrl='',pendingAvatarFile=null;
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const initials=(name,email)=>((name?.trim()||email?.split('@')[0]||'C').split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()).join(''));
function showMessage(text,type='success',target=messageBox){target.textContent=text;target.className=`message show ${type}`}
function clearMessage(target=messageBox){target.textContent='';target.className='message'}
function loading(button,on,text){if(!button.dataset.original)button.dataset.original=button.textContent;button.disabled=on;button.textContent=on?text:button.dataset.original}
function applyAvatar(el,url,fallback){el.textContent=fallback;el.style.backgroundImage='';el.style.color='';if(!url)return;const img=new Image();img.onload=()=>{el.style.backgroundImage=`url("${url.replace(/"/g,'')}")`;el.style.color='transparent'};img.src=url}
async function avatarUrlFor(user){const path=user?.user_metadata?.avatar_path;if(path){const {data}=await supabaseClient.storage.from(AVATAR_BUCKET).createSignedUrl(path,2592000);if(data?.signedUrl)return data.signedUrl}return user?.user_metadata?.avatar_url||''}
function showAuth(name){clearMessage();['login','signup','resend','reset','new-password'].forEach(x=>$(`${x}-form`).classList.toggle('hidden',x!==name));document.querySelector('.tabs').classList.toggle('hidden',!['login','signup'].includes(name));$('login-tab').classList.toggle('active',name==='login');$('signup-tab').classList.toggle('active',name==='signup')}
function showSection(name){document.querySelectorAll('.portal-section').forEach(x=>x.classList.add('hidden'));document.querySelectorAll('.nav-button').forEach(x=>x.classList.toggle('active',x.dataset.section===name));$(`section-${name}`).classList.remove('hidden');if(name==='private')loadPosts(true);if(name==='capsules')loadCapsules();if(name==='members')loadMembers();window.scrollTo({top:0,behavior:'smooth'})}
function formatDate(value){return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(value))}
function empty(text){return `<div class="empty-state">${esc(text)}</div>`}
async function getMembership(){const {data,error}=await supabaseClient.from('campfire_members').select('id,campfire_id,role,status,campfires(name,invite_code_hint)').eq('user_id',currentUser.id).eq('status','active').maybeSingle();if(error)throw error;return data}
async function renderUser(user){currentUser=user;const name=user.user_metadata?.full_name?.trim()||'Family Member',fallback=initials(name,user.email);resolvedAvatarUrl=await avatarUrlFor(user);$('welcome-heading').textContent=`Welcome back, ${name}.`;$('profile-preview-name').textContent=name;$('profile-preview-email').textContent=user.email||'';$('profile-name').value=name;$('profile-email').value=user.email||'';applyAvatar($('avatar-display'),resolvedAvatarUrl,fallback);applyAvatar($('profile-avatar-preview'),resolvedAvatarUrl,fallback)}
async function enterDashboard(user){authView.classList.add('hidden');dashboardView.classList.remove('hidden');await renderUser(user);try{currentMembership=await getMembership();if(!currentMembership){showMessage('Your account is not connected to a Campfire yet. Confirm that you used the correct family code, or run the Campfire database setup.','error',dashboardMessage);return}await Promise.all([loadPosts(false),loadCapsules()]);showSection('feed')}catch(error){showMessage('Campfire needs its Supabase database setup before family features can load. Run the included supabase-setup.sql file in Supabase SQL Editor.','error',dashboardMessage);console.error(error)}}
function loggedOut(){currentUser=null;currentMembership=null;dashboardView.classList.add('hidden');authView.classList.remove('hidden');showAuth('login')}
$('login-tab').onclick=()=>showAuth('login');$('signup-tab').onclick=()=>showAuth('signup');$('forgot-password').onclick=()=>showAuth('reset');$('open-resend-confirmation').onclick=()=>showAuth('resend');$('open-resend-confirmation-signup').onclick=()=>showAuth('resend');$('back-from-resend').onclick=()=>showAuth('login');$('back-to-login').onclick=()=>showAuth('login');
document.querySelectorAll('.nav-button').forEach(b=>b.onclick=()=>showSection(b.dataset.section));
$('login-form').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button[type=submit]');loading(b,true,'Entering…');const {error}=await supabaseClient.auth.signInWithPassword({email:$('login-email').value.trim(),password:$('login-password').value});loading(b,false);if(error)showMessage(error.message,'error')};
$('signup-form').onsubmit=async e=>{e.preventDefault();const suppliedCode=$('signup-code').value.trim().toUpperCase();if(suppliedCode!==FAMILY_CODE)return showMessage('Invalid family code. Please contact a family member for the invitation code.','error');const b=e.currentTarget.querySelector('button[type=submit]');loading(b,true,'Joining…');const {data,error}=await supabaseClient.auth.signUp({email:$('signup-email').value.trim(),password:$('signup-password').value,options:{data:{full_name:$('signup-name').value.trim(),campfire_code:FAMILY_CODE},emailRedirectTo:PRODUCTION_URL}});loading(b,false);if(error)return showMessage(error.message,'error');e.currentTarget.reset();showMessage(data.session?'Welcome to Campfire.':'Account created. Confirm your email, then log in.')};
$('resend-form').onsubmit=async e=>{e.preventDefault();const {error}=await supabaseClient.auth.resend({type:'signup',email:$('resend-email').value.trim(),options:{emailRedirectTo:PRODUCTION_URL}});error?showMessage(error.message,'error'):showMessage('Confirmation email sent.')};
$('reset-form').onsubmit=async e=>{e.preventDefault();const {error}=await supabaseClient.auth.resetPasswordForEmail($('reset-email').value.trim(),{redirectTo:PRODUCTION_URL});error?showMessage(error.message,'error'):showMessage('Password reset email sent.')};
$('new-password-form').onsubmit=async e=>{e.preventDefault();const {error}=await supabaseClient.auth.updateUser({password:$('new-password').value});error?showMessage(error.message,'error'):showMessage('Password updated.')};
$('logout-button').onclick=()=>supabaseClient.auth.signOut();
$('post-form').onsubmit=async e=>{e.preventDefault();if(!currentMembership)return;const b=e.currentTarget.querySelector('button');loading(b,true,'Sharing…');const {error}=await supabaseClient.from('campfire_posts').insert({campfire_id:currentMembership.campfire_id,author_id:currentUser.id,content:$('post-content').value.trim(),visibility:$('post-visibility').value});loading(b,false);if(error)return showMessage(error.message,'error',dashboardMessage);e.currentTarget.reset();$('post-visibility').value='family';await loadPosts(false);showMessage('Your post was shared.','success',dashboardMessage)};
async function loadPosts(privateOnly=false){if(!currentMembership)return;let q=supabaseClient.from('campfire_posts').select('id,content,visibility,created_at,author_id').eq('campfire_id',currentMembership.campfire_id).order('created_at',{ascending:false});if(privateOnly)q=q.eq('visibility','private').eq('author_id',currentUser.id);else q=q.eq('visibility','family');const {data,error}=await q;if(error){console.error(error);return}const users=[...new Set((data||[]).map(p=>p.author_id))];const profiles={};await Promise.all(users.map(async id=>{const {data:u}=await supabaseClient.rpc('get_member_profile',{profile_user_id:id});if(u?.[0])profiles[id]=u[0]}));const target=privateOnly?$('private-list'):$('feed-list');target.innerHTML=data?.length?data.map(p=>postHtml(p,profiles[p.author_id])).join(''):empty(privateOnly?'You have not written any private posts yet.':'The fire is quiet. Share the first family update.');if(!privateOnly&&data?.length){const old=data[data.length-1];$('memory-title').textContent=`A memory from ${formatDate(old.created_at).split(',')[0]}`;$('memory-copy').textContent=old.content.slice(0,180)}}
function postHtml(post,profile={}){const name=profile.full_name||'Family Member',avatar=profile.avatar_url||'',fallback=initials(name,'');return `<article class="post-card"><div class="post-head"><div class="mini-avatar" ${avatar?`style="background-image:url('${esc(avatar)}');color:transparent"`:''}>${esc(fallback)}</div><div class="post-meta"><h3>${esc(name)}</h3><p>${esc(formatDate(post.created_at))}</p></div><span class="privacy-pill">${post.visibility==='private'?'🔒 Only me':'🔥 Family'}</span></div><div class="post-body">${esc(post.content)}</div></article>`}
$('capsule-form').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button');loading(b,true,'Sealing…');const {error}=await supabaseClient.from('time_capsules').insert({campfire_id:currentMembership.campfire_id,creator_id:currentUser.id,title:$('capsule-title').value.trim(),message:$('capsule-message').value.trim(),recipient_label:$('capsule-recipient').value.trim()||'Whole family',unlock_at:new Date(`${$('capsule-date').value}T00:00:00`).toISOString()});loading(b,false);if(error)return showMessage(error.message,'error',dashboardMessage);e.currentTarget.reset();await loadCapsules();showMessage('Your time capsule has been sealed.','success',dashboardMessage)};
async function loadCapsules(){if(!currentMembership)return;const {data,error}=await supabaseClient.from('time_capsules').select('*').eq('campfire_id',currentMembership.campfire_id).order('unlock_at');if(error)return;const now=Date.now();$('capsule-list').innerHTML=data?.length?data.map(c=>{const locked=new Date(c.unlock_at).getTime()>now;return `<article class="capsule-card ${locked?'locked':''}"><p class="capsule-date">${locked?'🔒 Unlocks':'🔥 Opened'} ${esc(new Date(c.unlock_at).toLocaleDateString())}</p><h3>${esc(c.title)}</h3><p class="muted">For ${esc(c.recipient_label)}</p><p class="capsule-message">${locked?'This message is safely sealed until its unlock date.':esc(c.message)}</p></article>`}).join(''):empty('No time capsules have been sealed yet.');}
async function loadMembers(){if(!currentMembership)return;const {data,error}=await supabaseClient.rpc('list_campfire_members',{target_campfire_id:currentMembership.campfire_id});if(error)return showMessage(error.message,'error',dashboardMessage);$('member-list').innerHTML=data?.length?data.map(m=>`<article class="member-card"><div class="mini-avatar" ${m.avatar_url?`style="background-image:url('${esc(m.avatar_url)}');color:transparent"`:''}>${esc(initials(m.full_name,m.email))}</div><h3>${esc(m.full_name||'Family Member')}</h3><p class="muted">${esc(m.role||'member')}</p></article>`).join(''):empty('No family members found.');}
$('profile-avatar-file').onchange=e=>{pendingAvatarFile=e.target.files?.[0]||null;$('selected-file-name').textContent=pendingAvatarFile?.name||'No photo selected';if(pendingAvatarFile)applyAvatar($('profile-avatar-preview'),URL.createObjectURL(pendingAvatarFile),initials($('profile-name').value,currentUser.email))};
$('remove-profile-photo').onclick=async()=>{await supabaseClient.auth.updateUser({data:{...currentUser.user_metadata,avatar_path:'',avatar_url:''}});location.reload()};
$('profile-form').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button[type=submit]');loading(b,true,'Saving…');try{let path=currentUser.user_metadata?.avatar_path||'';if(pendingAvatarFile){const ext=(pendingAvatarFile.name.split('.').pop()||'jpg').toLowerCase();path=`${currentUser.id}/profile.${ext}`;const {error}=await supabaseClient.storage.from(AVATAR_BUCKET).upload(path,pendingAvatarFile,{upsert:true,contentType:pendingAvatarFile.type});if(error)throw error}const {data,error}=await supabaseClient.auth.updateUser({data:{...currentUser.user_metadata,full_name:$('profile-name').value.trim(),avatar_path:path,avatar_url:''}});if(error)throw error;await renderUser(data.user);showMessage('Profile saved.','success',dashboardMessage)}catch(error){showMessage(error.message,'error',dashboardMessage)}finally{loading(b,false)}};
function setTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem('campfire-theme',theme);$('theme-button').textContent=theme==='light'?'☾':'☀'}setTheme(localStorage.getItem('campfire-theme')||'dark');$('theme-button').onclick=()=>setTheme(document.documentElement.dataset.theme==='light'?'dark':'light');
supabaseClient.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY'){authView.classList.remove('hidden');dashboardView.classList.add('hidden');showAuth('new-password');return}session?.user?enterDashboard(session.user):loggedOut()});
(async()=>{const {data}=await supabaseClient.auth.getSession();data.session?.user?enterDashboard(data.session.user):loggedOut()})();